//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class learning
    {
        public int id { get; set; }
        public string file1 { get; set; }
        public string file2 { get; set; }
        public string file3 { get; set; }
        public string file4 { get; set; }
        public string file5 { get; set; }
        public string ddl { get; set; }
        public string ddl1 { get; set; }
        public string ddl2 { get; set; }
        public string Mddl1 { get; set; }
        public string Mddl2 { get; set; }
        public string Mddl3 { get; set; }
    }
}
