//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_ExhibitDetail
    {
        public long RecNo { get; set; }
        public string Comp_ReferenceNo { get; set; }
        public string ExhibitName { get; set; }
        public string ExhibitType { get; set; }
        public Nullable<decimal> WeightKG { get; set; }
        public Nullable<decimal> Dimen_L { get; set; }
        public Nullable<decimal> Dimen_W { get; set; }
        public Nullable<decimal> Dimen_H { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Returnable { get; set; }
        public string LoadDisPoint { get; set; }
        public string isActive { get; set; }
        public Nullable<System.DateTime> recTimeStamp { get; set; }
    }
}
