//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_Subscribe
    {
        public long EmailID { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecTimeDate { get; set; }
    }
}
