//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_B2BAcceptReq
    {
        public long B2BAcceptID { get; set; }
        public string B2BAIRefID { get; set; }
        public string B2BReqType { get; set; }
        public string B2BCompany { get; set; }
        public string B2BUniqueID { get; set; }
        public string B2BReqFromType { get; set; }
        public string B2BRequestCompName { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
