//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_B2BHall
    {
        public long B2BHallID { get; set; }
        public string B2BSection { get; set; }
        public string B2BHallName { get; set; }
        public string B2BHallSection { get; set; }
        public string B2BSlotTime { get; set; }
        public Nullable<System.DateTime> B2BSlotDate { get; set; }
        public string B2BStatus { get; set; }
        public string B2BStallNumber { get; set; }
        public string Defexpo_RefNo { get; set; }
        public string CompName { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string Payment { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public Nullable<System.DateTime> CancelationDate { get; set; }
    }
}
