//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_visitorsLogin
    {
        public long VisitorsID { get; set; }
        public string VisitorName { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string Unique_ID { get; set; }
        public string Category { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string TempRefNo { get; set; }
        public string otp_details { get; set; }
        public string RecInsTime { get; set; }
        public string Ticket { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> GstAmount { get; set; }
        public string Company { get; set; }
        public string TotalTicket { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Country { get; set; }
    }
}
