//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_Menu
    {
        public int MenuID { get; set; }
        public string Tooltip { get; set; }
        public int ParentMenuID { get; set; }
        public string MenuName { get; set; }
        public string Admin { get; set; }
        public string Company { get; set; }
        public string Factory { get; set; }
        public string Unit { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<System.DateTime> RecTime { get; set; }
        public string IsActive { get; set; }
        public string MenuUrl { get; set; }
        public string Class { get; set; }
        public string Fontawsomeclass { get; set; }
        public string Spanclass { get; set; }
        public string SuperAdmin { get; set; }
        public Nullable<System.DateTime> RecInsTIme { get; set; }
    }
}
