//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Admin_Users
    {
        public long Uid { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string UserPass { get; set; }
        public string isActive { get; set; }
        public string UserType { get; set; }
        public string Path { get; set; }
        public string InterestedArea { get; set; }
        public string MasterAllowed { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
