//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_EmbassyDiplomats
    {
        public int TrnID { get; set; }
        public string EmbassyId { get; set; }
        public string Embassy_UniqueId { get; set; }
        public string Category { get; set; }
        public string Name { get; set; }
        public string Name_Print { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Embassy { get; set; }
        public string Designation { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Photo { get; set; }
        public string CarNo { get; set; }
        public string ChassisNo { get; set; }
        public string EngineNo { get; set; }
        public string DriverName { get; set; }
        public string DriverFName { get; set; }
        public string CarLicence { get; set; }
        public string DriverPhoto { get; set; }
        public string DriverPhotoID { get; set; }
        public string DriverIDIssueDt { get; set; }
        public string DriverIDExpiryDt { get; set; }
        public string DriverIDNumber { get; set; }
        public string DriverIDPlace { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string AppByOrg { get; set; }
        public bool IsBadgeTableImported { get; set; }
        public string IsImported { get; set; }
        public string Country { get; set; }
        public Nullable<bool> IsVerified { get; set; }
    }
}
