//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_ExhibitorProduct
    {
        public int PID { get; set; }
        public Nullable<int> product_id { get; set; }
        public string comp_referenceno { get; set; }
        public string product_title { get; set; }
        public string img { get; set; }
        public string hall_stall { get; set; }
        public string weight { get; set; }
        public string dimensions { get; set; }
        public string description { get; set; }
        public string created { get; set; }
        public string modified { get; set; }
        public string status { get; set; }
        public string category { get; set; }
        public string sub_category { get; set; }
        public string sub_sub_category { get; set; }
    }
}
