//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_AircraftRate
    {
        public int RateId { get; set; }
        public Nullable<decimal> WeightInTon { get; set; }
        public string WeightDesc { get; set; }
        public Nullable<decimal> RateUSD { get; set; }
        public Nullable<decimal> RateINR { get; set; }
        public Nullable<decimal> DomesticDisRate { get; set; }
        public Nullable<decimal> SSIDisRate { get; set; }
        public string RateMonth { get; set; }
    }
}
