//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_ContractorCompany
    {
        public long ContID { get; set; }
        public string Contractor_UniqueID { get; set; }
        public string Exhibitor_ReferenceNO { get; set; }
        public string ContCompName { get; set; }
        public string ContCompName_Print { get; set; }
        public string ContAddress { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string CountryID { get; set; }
        public string CountryCode { get; set; }
        public string Currency { get; set; }
        public string Landline { get; set; }
        public string Fax { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Designation { get; set; }
        public string MobileNo { get; set; }
        public string EmailID { get; set; }
        public string BillingAddress { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string isActive { get; set; }
        public string InvoiceGen { get; set; }
        public string InvoiceNo { get; set; }
        public string Payment { get; set; }
        public string IPAddress { get; set; }
        public string GSTNo { get; set; }
        public string PanNo { get; set; }
        public string Website { get; set; }
        public string Type { get; set; }
        public string IsImported { get; set; }
        public Nullable<System.DateTime> ImportedOn { get; set; }
        public Nullable<bool> IsVerified { get; set; }
    }
}
