//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_ContractorBadge
    {
        public long Visitor_ID { get; set; }
        public string Visitor_UniqueId { get; set; }
        public string Contractor_UniqueID { get; set; }
        public string Visitor_Type { get; set; }
        public string Visitor_Title { get; set; }
        public string Visitor_Name { get; set; }
        public string Visitor_EmailID { get; set; }
        public string Visitor_Mobile { get; set; }
        public string Visitor_Sex { get; set; }
        public Nullable<System.DateTime> Visitor_DOB { get; set; }
        public string Visitor_Country_ID { get; set; }
        public string Visitor_Country { get; set; }
        public Nullable<long> Visitor_Identity_ID { get; set; }
        public string Visitor_Identity_IssueDt { get; set; }
        public string Visitor_Identity_ExpiryDt { get; set; }
        public string Visitor_Identity_No { get; set; }
        public string Visitor_Identity_IssuePlace { get; set; }
        public byte[] Visitor_Photo { get; set; }
        public Nullable<System.DateTime> RecTimeStamp { get; set; }
        public Nullable<bool> IsBadgeTableImported { get; set; }
        public string InvoiceGen { get; set; }
        public string InvoiceNo { get; set; }
        public string IsActive { get; set; }
        public string Payment { get; set; }
    }
}
