//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_BadgeCategory
    {
        public int category_Id { get; set; }
        public string category_Name { get; set; }
        public string Isactive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
