//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_Form
    {
        public long FormId { get; set; }
        public Nullable<int> SrNo { get; set; }
        public string FormName { get; set; }
        public string Date { get; set; }
        public string FormType { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
