//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_NodalOfficerRegistration
    {
        public long PassID { get; set; }
        public string NodelUniqueID { get; set; }
        public string NodelOfficerOrganization { get; set; }
        public Nullable<long> OrganizationID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string TempRefNo { get; set; }
        public Nullable<int> Quota { get; set; }
        public string NodalOfficerTitle { get; set; }
        public string NodelOfficerName { get; set; }
        public string NodalOfficerLName { get; set; }
        public string NodelOfficerDesignation { get; set; }
        public string NodelOfficerMobile { get; set; }
        public string Country { get; set; }
        public string IsActive { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> ChangePassword { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string Type { get; set; }
    }
}
