//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_AircraftDetail
    {
        public int RecNo { get; set; }
        public string Comp_ReferenceNo { get; set; }
        public Nullable<decimal> MTOWRange { get; set; }
        public string AircraftUsage { get; set; }
        public string ManufacturingYear { get; set; }
        public string AircraftType { get; set; }
        public string AircraftMake { get; set; }
        public string CurrentlyRegWith { get; set; }
        public string DesignRole { get; set; }
        public string EngineType { get; set; }
        public string ConstNo { get; set; }
        public string RegnNo { get; set; }
        public string WingSpan { get; set; }
        public string WheelTrack { get; set; }
        public string TrackWidth { get; set; }
        public string MinGroundClear { get; set; }
        public string WeightEmpty { get; set; }
        public string WeightMTOW { get; set; }
        public string WeightMaxtaxi { get; set; }
        public Nullable<decimal> Dimen_L { get; set; }
        public Nullable<decimal> Dimen_W { get; set; }
        public Nullable<decimal> Dimen_H { get; set; }
        public Nullable<decimal> NoOfCrafts { get; set; }
        public Nullable<decimal> DisplayCharges { get; set; }
        public Nullable<decimal> LandingCharges { get; set; }
        public string FlightType { get; set; }
        public string FuelDesc { get; set; }
        public string LubDesc { get; set; }
        public string GasDesc { get; set; }
        public string ImagePath { get; set; }
        public string ManualPath { get; set; }
        public string isActive { get; set; }
        public Nullable<System.DateTime> recTimeStamp { get; set; }
        public string InvoiceGen { get; set; }
        public string InvoiceNo { get; set; }
        public string AppByOrg { get; set; }
        public string OrgRemarks { get; set; }
        public Nullable<System.DateTime> AppTimeStamp { get; set; }
        public Nullable<int> adminid { get; set; }
    }
}
