//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_OTP
    {
        public long OtpID { get; set; }
        public string MobileNo { get; set; }
        public string OTPMobile { get; set; }
        public string EmailID { get; set; }
        public string EmailOTP { get; set; }
        public string OTPCategory { get; set; }
        public string OTPVerify { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> ExpiryTime { get; set; }
        public Nullable<System.DateTime> ReclnsTime { get; set; }
    }
}
