//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_InterestArea
    {
        public int Id { get; set; }
        public string InterestArea { get; set; }
        public string MenuId { get; set; }
        public string Flag { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Tooltip { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
