//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_WeaponDisp
    {
        public int TrnID { get; set; }
        public string Comp_UniqueID { get; set; }
        public decimal RecNo { get; set; }
        public string WeaponType { get; set; }
        public string WeaponRegNo { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Definition { get; set; }
        public string Description { get; set; }
        public string AppByOrg { get; set; }
        public string IsActive { get; set; }
        public System.DateTime RecInsTime { get; set; }
    }
}
