//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_WebinarRegistration
    {
        public long WebinarID { get; set; }
        public string Webinar_UniqueID { get; set; }
        public string Webinar_CompName { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string EmailID { get; set; }
        public string MobileNo { get; set; }
        public string Country_Code { get; set; }
        public string Country { get; set; }
        public string IsActive { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
