//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_Company
    {
        public long Comp_Id { get; set; }
        public string Comp_ReferenceNo { get; set; }
        public string Comp_Name { get; set; }
        public string Comp_Name_Print { get; set; }
        public string IsDirect_IsIndirect { get; set; }
        public string Comp_Address { get; set; }
        public string Comp_City { get; set; }
        public string Comp_State { get; set; }
        public Nullable<int> Comp_Country { get; set; }
        public string Comp_CountryCode { get; set; }
        public string Comp_PinCode { get; set; }
        public string Comp_LandlineNo { get; set; }
        public string Comp_FaxNo { get; set; }
        public string Comp_MobileNo { get; set; }
        public string Comp_HeadName { get; set; }
        public string Comp_HeadDesig { get; set; }
        public string Comp_HeadEmailId { get; set; }
        public string Comp_ContactTitle { get; set; }
        public string Comp_ContactName { get; set; }
        public string Comp_ContactLname { get; set; }
        public string Comp_ContactDesig { get; set; }
        public string Comp_ContactEmail { get; set; }
        public string Comp_ContactAddress { get; set; }
        public string Comp_ContactCity { get; set; }
        public string Comp_ContactState { get; set; }
        public string Comp_ContactPin { get; set; }
        public string Comp_ContactCountry { get; set; }
        public string Comp_isParent { get; set; }
        public string Comp_ParentUniqueId { get; set; }
        public string Comp_isActive { get; set; }
        public string Comp_ProductProfile { get; set; }
        public string Comp_Currency { get; set; }
        public string Comp_BillingAddress { get; set; }
        public string Comp_Logo { get; set; }
        public string Comp_Type { get; set; }
        public string Comp_ProductId { get; set; }
        public string Comp_ProductName { get; set; }
        public string Comp_ProductId1 { get; set; }
        public string Comp_ProductName1 { get; set; }
        public string Comp_ProductId2 { get; set; }
        public string Comp_ProductName2 { get; set; }
        public string Payment { get; set; }
        public string Comp_PAN { get; set; }
        public string Comp_GST { get; set; }
        public Nullable<int> AdminId { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> Comp_RegisterTime { get; set; }
        public Nullable<System.DateTime> Comp_LastUpdateTime { get; set; }
        public string WebsiteURL { get; set; }
        public Nullable<int> FinalPayment { get; set; }
        public string DirectoryEmail { get; set; }
        public Nullable<System.DateTime> DirectoryDate { get; set; }
        public Nullable<int> SubCompanyQuota { get; set; }
        public string ParentSpaceAllote { get; set; }
        public string CancelationType { get; set; }
        public string CancelationRemarks { get; set; }
        public Nullable<bool> PassMenuVisible { get; set; }
        public Nullable<bool> CatalogMenuVisible { get; set; }
        public string IsPavilion { get; set; }
        public string InterestedIN { get; set; }
        public string IsTradeAssociation { get; set; }
        public string TradeAssociationName { get; set; }
        public string Comp_Business { get; set; }
        public string IndirectParentRefNo { get; set; }
        public string others_contact_title { get; set; }
        public string others_contactname { get; set; }
        public string otherscontact_lname { get; set; }
        public string others_contactemail { get; set; }
        public string others_contact_mobile { get; set; }
        public string others_contact_language { get; set; }
        public string others_designation { get; set; }
        public string others_whatsapp_number { get; set; }
        public string nodal_WhatsAppNumber { get; set; }
        public string invoicing_address { get; set; }
        public string invoicing_company_name { get; set; }
        public string invoicing_pincode { get; set; }
        public string invoicingvat_gstnumber { get; set; }
        public string invoicing_title { get; set; }
        public string invoicing_contact_name { get; set; }
        public string invoicing_lastname { get; set; }
        public string invoicing_email { get; set; }
        public string invoicing_mobile { get; set; }
        public string invoicing_country { get; set; }
        public string invoicing_language { get; set; }
        public string invoicing_panNo { get; set; }
        public string other_company_business { get; set; }
        public Nullable<bool> msme_type { get; set; }
        public string msme_value { get; set; }
        public string msme_filepath { get; set; }
        public Nullable<bool> is_msme { get; set; }
        public Nullable<bool> startup_type { get; set; }
        public string startup_value { get; set; }
        public Nullable<bool> Is_sendReferenceNumber { get; set; }
        public string CountryExhibitors { get; set; }
        public string other_WhatsappCountryCode { get; set; }
        public string Invoicing_CountryCode { get; set; }
        public string Nodal_WhatsappCountryCode { get; set; }
        public string other_CountryCode { get; set; }
        public string Landline_CountryCode { get; set; }
        public string IsMobileVerify { get; set; }
        public string CompMobile_Otp { get; set; }
        public string Comp_countryCode1 { get; set; }
        public string PaymentCurrency { get; set; }
        public Nullable<int> IsAdmin { get; set; }
        public Nullable<decimal> ToatalAmount { get; set; }
        public Nullable<decimal> CatalougeAmt { get; set; }
        public Nullable<decimal> BulkDiscount { get; set; }
        public Nullable<decimal> MSMEDiscount { get; set; }
        public Nullable<decimal> CancellationCharge { get; set; }
        public Nullable<decimal> GSTOnAmount { get; set; }
        public Nullable<decimal> GSTAmt { get; set; }
        public Nullable<decimal> SGSTAmt { get; set; }
        public Nullable<decimal> CGSTAmt { get; set; }
        public Nullable<decimal> PenalAmt { get; set; }
        public Nullable<decimal> TotalPayable { get; set; }
        public Nullable<decimal> TotalRcvdAmt { get; set; }
        public Nullable<decimal> ToBePaid { get; set; }
        public Nullable<decimal> OctNovPenalOnAmt { get; set; }
        public Nullable<decimal> DecPenalOnAmt { get; set; }
        public Nullable<int> GSTFlag { get; set; }
        public string Panel_Flag { get; set; }
        public Nullable<int> CatalogueFlag { get; set; }
        public Nullable<decimal> CoExFee { get; set; }
        public Nullable<int> CoExQty { get; set; }
        public Nullable<int> CoExQtyFree { get; set; }
        public Nullable<int> CoExQtyPaid { get; set; }
        public Nullable<int> CoExType { get; set; }
        public Nullable<decimal> SpecialDiscount { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public Nullable<int> SubSubCategoryID { get; set; }
        public string Token_Key { get; set; }
        public string IsUpdate { get; set; }
    
        public virtual tbl_mst_Country tbl_mst_Country { get; set; }
    }
}
