//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_SpaceRate
    {
        public int RateID { get; set; }
        public string HallType { get; set; }
        public string SpaceType { get; set; }
        public string SpaceDesc { get; set; }
        public Nullable<decimal> RateUSD { get; set; }
        public Nullable<decimal> RateINR { get; set; }
        public Nullable<decimal> RateFINR { get; set; }
        public string Unit { get; set; }
        public string RateMonth { get; set; }
        public Nullable<int> MonthRate { get; set; }
    }
}
