//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_visitror_securekey
    {
        public long SecuerID { get; set; }
        public string visitors_ref_no { get; set; }
        public string secure_key { get; set; }
        public string unique_key { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> RecIncTime { get; set; }
    }
}
