//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_EquipmentOnRent
    {
        public int RentId { get; set; }
        public string Comp_UniqueId { get; set; }
        public Nullable<decimal> Size { get; set; }
        public string Itemcode { get; set; }
        public string ACCESSORIES { get; set; }
        public string SizeSpecification { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public string Cur { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> GSTTax { get; set; }
        public Nullable<decimal> GTotalCost { get; set; }
        public string InvoiceGen { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> Days { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
