//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_Media
    {
        public long Media_ID { get; set; }
        public string Media_ReferenceNo { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string Gender { get; set; }
        public string Organisation { get; set; }
        public string BusinessAddress { get; set; }
        public string HomeAddress { get; set; }
        public string City { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string EmailID { get; set; }
        public string MediaFunction { get; set; }
        public string TypeOfMedia { get; set; }
        public string DOB { get; set; }
        public byte[] Photo { get; set; }
        public string Photo_Path { get; set; }
        public string Media_AccreditationPath { get; set; }
        public Nullable<int> IdentityTypeId { get; set; }
        public string IdentityNo { get; set; }
        public string IdentityIssuePlace { get; set; }
        public Nullable<System.DateTime> IdentityIssueDate { get; set; }
        public Nullable<System.DateTime> IdentityExpiryDate { get; set; }
        public string CitizenCountry { get; set; }
        public string PressCardNo { get; set; }
        public string IssuingAuthority { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> MedRecInsTime { get; set; }
        public string AppByOrg { get; set; }
        public bool IsBadgeTableImported { get; set; }
        public string IsImported { get; set; }
        public string HomeAddressCity { get; set; }
        public string HomeAddressState { get; set; }
        public string HomeAddressPinCode { get; set; }
        public string OfficeAddressCity { get; set; }
        public string OfficeAddressState { get; set; }
        public string OfficeAddressPinCode { get; set; }
        public string LandlineCountryCode { get; set; }
        public string LandlineStateCode { get; set; }
        public string FaxCountryCode { get; set; }
        public string FaxStateNumber { get; set; }
        public string CurrentlyWorkingCountry { get; set; }
        public string Designation { get; set; }
        public string OtherTypeOfMedia { get; set; }
        public string OtherRoleInMedia { get; set; }
        public string Nationality { get; set; }
        public string CountryCode { get; set; }
        public string Relationship { get; set; }
        public string MotherName { get; set; }
        public Nullable<bool> IsSendReference { get; set; }
        public string StatusRemarks { get; set; }
        public string UserID { get; set; }
    }
}
