//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_PowerRate
    {
        public int PowRateId { get; set; }
        public string PowerType { get; set; }
        public string PowerDesc { get; set; }
        public Nullable<decimal> RateINR { get; set; }
        public Nullable<decimal> RateUSD { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
