//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_mst_Country()
        {
            this.tbl_mst_BusinessVisitor = new HashSet<tbl_mst_BusinessVisitor>();
            this.tbl_mst_Company = new HashSet<tbl_mst_Company>();
            this.tbl_mst_Enquiry = new HashSet<tbl_mst_Enquiry>();
            this.tbl_mst_GeneralVisitor = new HashSet<tbl_mst_GeneralVisitor>();
        }
    
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string IsActive { get; set; }
        public string CountryNameAndCountryCode { get; set; }
        public string Alpha3Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_mst_BusinessVisitor> tbl_mst_BusinessVisitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_mst_Company> tbl_mst_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_mst_Enquiry> tbl_mst_Enquiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_mst_GeneralVisitor> tbl_mst_GeneralVisitor { get; set; }
    }
}
