//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_design
    {
        public int Id { get; set; }
        public string hall_name { get; set; }
        public Nullable<int> design_row_index { get; set; }
        public Nullable<int> design_column_index { get; set; }
        public string design_border { get; set; }
        public string border_height { get; set; }
        public string border_width { get; set; }
        public Nullable<bool> Isactive { get; set; }
    }
}
