//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_DiscussionContest
    {
        public int ContestId { get; set; }
        public string TokenNo { get; set; }
        public string ContryName { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string IdentityType { get; set; }
        public string IdentityNumber { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecDateTime { get; set; }
    }
}
