//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_State
    {
        public long StateID { get; set; }
        public string StateName { get; set; }
        public Nullable<long> CountryId { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
