//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_B2B
    {
        public long B2BID { get; set; }
        public string Visitor_CompName { get; set; }
        public string Visitor_UniqueId { get; set; }
        public string ToWhoID { get; set; }
        public string ToWhoName { get; set; }
        public string MailSend { get; set; }
        public string Purpose { get; set; }
        public string CompProfile { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
    }
}
