//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_SpaceLog
    {
        public int LogId { get; set; }
        public Nullable<int> HallID { get; set; }
        public string Section { get; set; }
        public string StallNumber { get; set; }
        public Nullable<decimal> StallSize { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusOn { get; set; }
        public string Comp_RefNo { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> MSMEDiscount { get; set; }
        public string MSMEDiscountRemarks { get; set; }
        public Nullable<decimal> OtherDiscount { get; set; }
        public string OtherDiscountRemarks { get; set; }
        public Nullable<decimal> PayableAmount { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> NetPayable { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
