//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_PowerReq
    {
        public int PowerId { get; set; }
        public string Comp_UniqueID { get; set; }
        public string PowerFor { get; set; }
        public string PowerType { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Phase { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<System.DateTime> PreForm { get; set; }
        public Nullable<System.DateTime> PreTo { get; set; }
        public Nullable<System.DateTime> PostForm { get; set; }
        public Nullable<System.DateTime> PostTo { get; set; }
        public string AppByOrg { get; set; }
        public string InvoiceGen { get; set; }
        public string InvoiceNo { get; set; }
        public string CancelStatus { get; set; }
        public Nullable<int> adminid { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
