//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_Directory
    {
        public long CompanyId { get; set; }
        public string Comp_UniqueId { get; set; }
        public string NameOfOrganization { get; set; }
        public string StandNo { get; set; }
        public string HallNo { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pincode { get; set; }
        public string Country { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string NameoftheChiefExecutiveOfficer { get; set; }
        public string Designation { get; set; }
        public string Contactperson { get; set; }
        public string ContactDesignation { get; set; }
        public string CompanyList { get; set; }
        public string CompLogo1 { get; set; }
        public string CompLogo { get; set; }
        public string IsAppOrg { get; set; }
        public string Payment { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> RecTimeIns { get; set; }
        public string Type { get; set; }
        public string IsFreeze { get; set; }
    }
}
