//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ForeignDelegateMettingSetupDetails
    {
        public int SetUpDetailID { get; set; }
        public Nullable<int> SetUpID { get; set; }
        public string ReferenceNo { get; set; }
        public string Purpose { get; set; }
        public string DocumentPath { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> ApproveReject { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
