//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_exhibitor_Catalouge
    {
        public int id { get; set; }
        public Nullable<int> exhibitor_id { get; set; }
        public string comp_referenceno { get; set; }
        public string token_key { get; set; }
        public string User_name { get; set; }
        public string exhibitor_name { get; set; }
        public string company_brief { get; set; }
        public string additional_company_brief { get; set; }
        public string website { get; set; }
        public string exhibitor_country_code { get; set; }
        public string exhibitor_phone { get; set; }
        public string exhibitor_email { get; set; }
        public string facebook_url { get; set; }
        public string twitter_tag { get; set; }
        public string linkedin_url { get; set; }
        public string instagram { get; set; }
        public string exhibitor_logo { get; set; }
        public string short_company_name { get; set; }
        public string address { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string pincode { get; set; }
        public string hall_and_stall { get; set; }
        public string nodal_officer_name { get; set; }
        public string nodal_officer_email { get; set; }
        public string nodal_officer_designation { get; set; }
        public string nodal_officer_countrycode { get; set; }
        public string nodal_officer_phone { get; set; }
        public string ceo_name { get; set; }
        public string ceo_email { get; set; }
        public string ceo_designation { get; set; }
        public string ceo_countrycode { get; set; }
        public string ceo_phone { get; set; }
        public string exhibitor_fax_country_code { get; set; }
        public string exhibitor_fax { get; set; }
        public string exhibitor_type { get; set; }
        public string payment_type { get; set; }
        public string created { get; set; }
        public string modified { get; set; }
        public string status { get; set; }
        public string category { get; set; }
        public string sub_category { get; set; }
        public string sub_sub_category { get; set; }
        public string exhibitor_text2 { get; set; }
    }
}
