//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_LoFeedback_form
    {
        public int ID { get; set; }
        public Nullable<int> LoID { get; set; }
        public string LoName { get; set; }
        public string Question_detail { get; set; }
        public string Correct_answer { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
