//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_defexpolist_2018
    {
        public long DefCompID { get; set; }
        public string comp_name { get; set; }
        public string country_name { get; set; }
        public string ceo_name { get; set; }
        public string ceo_designation { get; set; }
        public string ceo_email_address { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string nodal_officer_name { get; set; }
        public string nodal_designation { get; set; }
        public string nodal_email { get; set; }
    }
}
