//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_ExRep
    {
        public long Visitor_ID { get; set; }
        public string Visitor_UniqueId { get; set; }
        public string ParentUniqueID { get; set; }
        public string Comp_UniqueId { get; set; }
        public string Visitor_Company { get; set; }
        public string Visitor_Type { get; set; }
        public string Visitor_Title { get; set; }
        public string Visitor_FName { get; set; }
        public string Visitor_LName { get; set; }
        public string Visitor_Name_Print { get; set; }
        public string Visitor_Designation { get; set; }
        public string Visitor_Sex { get; set; }
        public string Visitor_EmailID { get; set; }
        public Nullable<long> Visitor_Country_ID { get; set; }
        public string Visitor_Country { get; set; }
        public string Visitor_Mobile { get; set; }
        public string Visitor_DOB { get; set; }
        public Nullable<long> Visitor_Identity_ID { get; set; }
        public string Visitor_Identity_IssueDt { get; set; }
        public string Visitor_Identity_ExpiryDt { get; set; }
        public string Visitor_Identity_No { get; set; }
        public string Visitor_Identity_IssuePlace { get; set; }
        public byte[] Visitor_Photo { get; set; }
        public string Photo_Path { get; set; }
        public Nullable<System.DateTime> VRecTimeStamp { get; set; }
        public bool IsBadgeTableImported { get; set; }
        public string NewReg { get; set; }
        public string Payment { get; set; }
        public string IsImported { get; set; }
        public Nullable<System.DateTime> ImportedOn { get; set; }
        public string BMSImported { get; set; }
        public Nullable<bool> IsVerified { get; set; }
    }
}
