//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LODetails
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string LO_Name { get; set; }
        public string Organization { get; set; }
        public string LO_MobileNo { get; set; }
        public string Del_Contact_No { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string IsActive { get; set; }
    }
}
