//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_Media_Images
    {
        public long GalleryID { get; set; }
        public string ImgName { get; set; }
        public string ImgDescription { get; set; }
        public string ImgUrl { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTmie { get; set; }
    }
}
