//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_ConfrenceHall
    {
        public long ConfrenceHallID { get; set; }
        public string ConfrenceSection { get; set; }
        public string ConfrenceHallName { get; set; }
        public string ConfrenceHallSection { get; set; }
        public string ConfrenceSlotTime { get; set; }
        public Nullable<System.DateTime> ConfrenceSlotDate { get; set; }
        public string ConfrenceStatus { get; set; }
        public string ConfrenceStallNumber { get; set; }
        public string Defexpo_RefNo { get; set; }
        public string CompName { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string Payment { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string Test { get; set; }
        public Nullable<System.DateTime> CancelationDate { get; set; }
    }
}
