//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_agenda
    {
        public int ID { get; set; }
        public string AgendaTitle { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string AgendaCategory { get; set; }
        public string Location { get; set; }
        public string AssociatedSpeakers { get; set; }
        public string Description { get; set; }
        public string RegisterWebinar { get; set; }
        public string Forums { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
