//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_Registrationrate
    {
        public int Amount_ID { get; set; }
        public Nullable<decimal> Amount_INR { get; set; }
        public string Currency_INR { get; set; }
        public Nullable<decimal> Amount_USD { get; set; }
        public string Currency_USD { get; set; }
        public string month_wise { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecsInTime { get; set; }
    }
}
