//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_GeneralVisitor
    {
        public long Visitor_ID { get; set; }
        public string Visitor_UniqueId { get; set; }
        public string Visitor_Type { get; set; }
        public string Visitor_Title { get; set; }
        public string Visitor_Name { get; set; }
        public string Visitor_LName { get; set; }
        public string Visitor_Sex { get; set; }
        public string Visitor_EmailID { get; set; }
        public string Visitor_Address { get; set; }
        public string Visitor_City { get; set; }
        public string Visitor_State { get; set; }
        public int Visitor_Country_ID { get; set; }
        public string Visitor_CountryCode { get; set; }
        public string Visitor_Mobile { get; set; }
        public string Visitor_DOB { get; set; }
        public long Visitor_Identity_ID { get; set; }
        public string Visitor_Identity_IssueDt { get; set; }
        public string Visitor_Identity_ExpiryDt { get; set; }
        public string Visitor_Identity_No { get; set; }
        public string Visitor_Identity_IssuePlace { get; set; }
        public string VComp_Name { get; set; }
        public Nullable<System.DateTime> VRecTimeStamp { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> TicketRate { get; set; }
        public string Payment { get; set; }
        public string InvoiceRep { get; set; }
        public string InvoiceNo { get; set; }
        public string Designation { get; set; }
        public bool IsBadgeTableImported { get; set; }
        public string IsIssued { get; set; }
        public string IsPaid { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PID { get; set; }
        public string GSTNo { get; set; }
        public string Visitor_VisitDay { get; set; }
        public string IsImported { get; set; }
        public Nullable<System.DateTime> ImportedDate { get; set; }
        public Nullable<bool> IsSmsSend { get; set; }
    
        public virtual tbl_mst_Country tbl_mst_Country { get; set; }
    }
}
