//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_HallSize
    {
        public int HallID { get; set; }
        public string SpaceID { get; set; }
        public string Section { get; set; }
        public string SectionCategory { get; set; }
        public string Height { get; set; }
        public string Width { get; set; }
        public string StallNumber { get; set; }
        public string Size { get; set; }
        public string StallSize { get; set; }
        public string Type { get; set; }
        public string TypeName { get; set; }
        public string Status { get; set; }
        public string Comp_ReferenceNo { get; set; }
        public string CompName { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> MonthRate { get; set; }
        public string IsAcquired { get; set; }
        public string IsLock { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> CancelationDate { get; set; }
        public string UserId { get; set; }
    
        public virtual tbl_mst_HallSize tbl_mst_HallSize1 { get; set; }
        public virtual tbl_mst_HallSize tbl_mst_HallSize2 { get; set; }
    }
}
