//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AllotementSpace
    {
        public int AllotementSpaceID { get; set; }
        public string ReferenceNo { get; set; }
        public string IndirectReferenceNo { get; set; }
        public string HallNumber { get; set; }
        public string StallNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
