//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_VisitorTicketCount
    {
        public long VisitorCountID { get; set; }
        public Nullable<long> TicketCount { get; set; }
        public string CountryName { get; set; }
        public string Currency { get; set; }
        public string Amount { get; set; }
        public string VisitorRefNo { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public Nullable<System.DateTime> IsUsedTime { get; set; }
    }
}
