//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_Enquiry
    {
        public long EnquiryID { get; set; }
        public string Name { get; set; }
        public string Company_Name { get; set; }
        public Nullable<int> Country { get; set; }
        public string Address { get; set; }
        public string Contact_No { get; set; }
        public string Email { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public string rID { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string EmailOTP { get; set; }
    
        public virtual tbl_mst_Country tbl_mst_Country { get; set; }
    }
}
