//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_Embassy
    {
        public int EmbassyId { get; set; }
        public string AIReferenceNo { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Country { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string EmailID { get; set; }
        public string Pwd { get; set; }
        public string Address { get; set; }
        public string Photo { get; set; }
        public string Mobile { get; set; }
        public string NodelPersonMobile { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string Form { get; set; }
        public string AppByOrg { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string TempRefNo { get; set; }
        public bool IsActive { get; set; }
        public string CountryCode { get; set; }
        public string Delegate { get; set; }
        public string DelegateNodelPerson { get; set; }
        public string DelegateNodelEmail { get; set; }
    }
}
