//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_inner_mst_design
    {
        public long Id { get; set; }
        public string hall_name { get; set; }
        public string hall_value { get; set; }
        public Nullable<int> inner_hall_row_index { get; set; }
        public Nullable<int> inner_hall_column_index { get; set; }
        public string inner_hall_design_border { get; set; }
        public string inner_hall_border_height { get; set; }
        public string inner_hall_border_width { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
