//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_MouEvent
    {
        public int ID { get; set; }
        public string EntityName { get; set; }
        public string EmailID { get; set; }
        public string PhoneNo { get; set; }
        public string Description { get; set; }
        public string PropsedtoDo { get; set; }
        public string TickTitle { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string Comp_ReferenceNo { get; set; }
    }
}
