//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTable
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string LName { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string Comp_Name { get; set; }
        public string Designation { get; set; }
        public string Mobile { get; set; }
        public string Category { get; set; }
        public string ID_Type { get; set; }
        public string ID_Number { get; set; }
        public string Passport_Issue_Date { get; set; }
        public string Passport_Expiry_Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string SendLink { get; set; }
        public string Photo_Name { get; set; }
        public string Photo_Path { get; set; }
        public Nullable<int> Assigned_Quota { get; set; }
        public Nullable<int> Balance_Quota { get; set; }
        public Nullable<int> Processing { get; set; }
        public Nullable<int> Approved { get; set; }
        public Nullable<int> Declined { get; set; }
        public Nullable<int> Printed { get; set; }
        public Nullable<int> Delivered { get; set; }
        public Nullable<bool> IsVerified { get; set; }
    }
}
