//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrdoWeb.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PassStatus
    {
        public Nullable<long> Comp_Id { get; set; }
        public string Comp_ReferenceNo { get; set; }
        public string Comp_Name { get; set; }
        public int Status_Id { get; set; }
        public Nullable<int> Delivered { get; set; }
        public Nullable<int> Printed { get; set; }
        public Nullable<int> Decliend { get; set; }
        public Nullable<int> Approved { get; set; }
        public Nullable<int> Processing { get; set; }
        public Nullable<int> Balance_Quota { get; set; }
        public Nullable<int> Comp_Country { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public string category_Name { get; set; }
        public Nullable<int> Quota { get; set; }
    }
}
